version: "3"

services:
    neo4j-test:
        image: neo4j:latest
        container_name: neo4j-db-test
        restart: unless-stopped
        environment:
            - NEO4J_AUTH=${NEO4J_AUTH}
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - /home/rocky/neo4j/data:/data
            - /home/rocky/neo4j/logs:/logs
            - /home/rocky/neo4j/plugins:/plugins
            - /home/rocky/neo4j/import:/import

    app-test:
        build: ./
        container_name: uee.life-test
        restart: unless-stopped
        command:
            "npm run start"
        ulimits:
            nofile:
                soft: 4096
                hard: 4096
        depends_on:
            - neo4j-test
    
    nginx-test:
        image: nginx
        container_name: nginx_uee.life-test
        ports:
            - "8090:80"
        volumes:
            - ./nginx/nginx-test.conf:/etc/nginx/nginx.conf
        depends_on:
            - app-test