version: "3"

services:
    neo4j:
        image: neo4j:latest
        container_name: neo4j-db
        restart: unless-stopped
        environment:
            - NEO4J_AUTH=${NEO4J_AUTH}
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - /home/rocky/neo4j/data:/data
            - /home/rocky/neo4j/logs:/logs
            - /home/rocky/neo4j/plugins:/plugins
            - /home/rocky/neo4j/import:/import

    app:
        build: ./
        container_name: uee-life
        restart: unless-stopped
        command:
            "npm run start"
        ulimits:
            nofile:
                soft: 4096
                hard: 4096
        depends_on:
            - neo4j
    
    nginx:
        image: nginx
        container_name: uee-life-nginx
        ports:
            - "8090:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app