version: "3"

services:
    app:
        build: ./
        container_name: uee-life-test
        restart: unless-stopped
        command:
            "npm run start"
        ulimits:
            nofile:
                soft: 4096
                hard: 4096
    
    nginx:
        image: nginx
        container_name: uee-life-test-nginx
        ports:
            - "8090:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app